# Generated by Django 3.2.7 on 2021-10-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retaile_price',
            new_name='retail_price',
        ),
    ]
