# Generated by Django 3.2.7 on 2021-10-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_retaile_price_book_retail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubname', models.CharField(max_length=255, unique=True, verbose_name='出版社')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.pub_name'),
        ),
    ]
