# Generated by Django 3.2.7 on 2021-10-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20211001_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='public',
        ),
    ]
