# Generated by Django 3.2.7 on 2021-10-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_extenduserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='books',
            field=models.ManyToManyField(to='index.BOOk'),
        ),
    ]
