# Generated by Django 3.2.7 on 2021-10-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_userinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfBook',
            fields=[
                ('title', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='书籍名称')),
                ('author', models.CharField(max_length=24, verbose_name='作者')),
                ('desc', models.CharField(default='无描述', max_length=255, verbose_name='简介')),
                ('img_ul', models.CharField(default='无路径', max_length=255, verbose_name='图片路径')),
            ],
        ),
    ]
