# Generated by Django 3.2.7 on 2021-10-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_rename_desc_mfbook_desc_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBook',
            fields=[
                ('title', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='书籍名称')),
                ('author', models.CharField(max_length=24, null=True, verbose_name='作者')),
                ('description', models.CharField(default='无描述', max_length=255, null=True, verbose_name='简介')),
                ('img_ul', models.CharField(default='无路径', max_length=255, null=True, verbose_name='图片路径')),
            ],
        ),
        migrations.RenameField(
            model_name='mfbook',
            old_name='desc_test',
            new_name='description',
        ),
    ]
