# Generated by Django 3.2.8 on 2021-10-19 01:00


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_remove_extenduserinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendUserInfo',
        ),
    ]
