# Generated by Django 3.2.8 on 2021-10-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_delete_extenduserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=1, max_length=24, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=24, verbose_name='用户昵称'),
        ),
    ]
