# Generated by Django 3.2.8 on 2021-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20211019_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxbook',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='作者'),
        ),
    ]
