# Generated by Django 3.2.8 on 2021-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_cxbook_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxbook',
            name='num',
            field=models.IntegerField(null=True, verbose_name='排名'),
        ),
        migrations.AddField(
            model_name='djbook',
            name='num',
            field=models.IntegerField(null=True, verbose_name='排名'),
        ),
        migrations.AddField(
            model_name='dybook',
            name='num',
            field=models.IntegerField(null=True, verbose_name='排名'),
        ),
        migrations.AddField(
            model_name='mfbook',
            name='num',
            field=models.IntegerField(null=True, verbose_name='排名'),
        ),
        migrations.AddField(
            model_name='xsbook',
            name='num',
            field=models.IntegerField(null=True, verbose_name='排名'),
        ),
    ]
