# Generated by Django 3.2.8 on 2021-10-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20211019_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxbook',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='djbook',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='dybook',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='mfbook',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='xsbook',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='作者'),
        ),
    ]
