# Generated by Django 3.2.8 on 2021-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_auto_20211019_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbook',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='作者'),
        ),
    ]
